variables:
  build-pipeline: JENKINS_JOB_1

build-release:
  tag: build
  variables:
    name: "sachin tendulakar"
    address: "mumbai"
    locality: "pune"
    sports: "cricket"
  script:
    - echo "name = <name>, address = <address>, locality= <locality>, sports= <sports>"
