apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: sumedh-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
      annotations:
        sidecar.isito.io/inject: "false"
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: jenkins-sa-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          volumeMounts:
            - name: jenkins-pv-storage
              mountPath: /var/jenkins_home
              subPath: "jenkins_home"
      volumes:
        - name: jenkins-pv-storage
          persistentVolumeClaim:
            claimName: sumedh-devops-jenkins-pvc
